# Generated by Django 5.2.16 on 2026-10-09 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_learning_track'),
        ('education', '0004_course_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_access_mode',
            field=models.CharField(choices=[('TRACK_DEFAULT', 'Track Default'), ('CUSTOM', 'Custom')], default='TRACK_DEFAULT', max_length=20),
        ),
        migrations.CreateModel(
            name='UserCourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='education.course')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_course_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_access')],
            },
        ),
    ]
