# Generated by Django 5.2.16 on 2026-10-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_test_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='competency',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='adaptive_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
